# action.yml
name: 'TSL Validate'
description: 'Validate the Template SIMD Library Generator'
inputs:
  image:
    description: "Name of the image to use for the validation."
    required: true
    type: string
  python-version:
    description: "Python version to use for the validation, e.g., '3.8'."
    required: true
    type: string
outputs:
  name:
    description: 'Name of the generated files.'
  out:
    description: 'Path to the generated files.'
  msg:
    description: 'Verbose message from the action.'
  success:
    description: 'Whether the action was successful (1, 0 otherwise).'
  failout:
    description: 'Path to the failed output.'
environment: TSL_DOCKER
runs:
  using: 'docker'
  image: 'docker://jpietrzyktud/tsl_validation:latest'
  args:
    - ${{ inputs.python-version }}